// The numbers the site publishes must be the numbers in the committed run.
// evidence.json is generated by bench/dcn/evidence.py; this recomputes the
// headline from bench/results/per_dataset.csv and compares, so the page can
// never quietly disagree with the data behind it.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { parseCSV } from '../site/js/csv.js';
import { averageRanks, beyondLuck, boostingVerdict, evidenceFor, evidenceSentence, formatP, rankChart }
  from '../site/js/evidence.js';
import { loadTaxonomyFromDisk } from './helpers.js';

const T = loadTaxonomyFromDisk();
const EV = T.EVIDENCE;
const ROOT = new URL('../', import.meta.url);

function readTable(path) {
  const { head, body } = parseCSV(fs.readFileSync(new URL(path, ROOT), 'utf8'));
  const index = Object.fromEntries(head.map((name, i) => [name, i]));
  return body.map(row => Object.fromEntries(head.map(name => {
    const raw = row[index[name]];
    const value = raw === '' ? null : Number(raw);
    return [name, Number.isNaN(value) ? raw : value];
  })));
}

const perDataset = () => readTable('bench/results/per_dataset.csv');

const median = (values) => {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = sorted.length / 2;
  return sorted.length % 2 ? sorted[Math.floor(mid)] : (sorted[mid - 1] + sorted[mid]) / 2;
};

test('the evidence file is present and describes its own run', () => {
  assert.ok(EV, 'site/taxonomy/evidence.json is missing');
  assert.match(EV.source_url, /^https:\/\/github\.com\//);
  assert.ok(EV.how.length > 40, 'the method has to be stated on the page');
  assert.ok(EV.datasets.length >= 20);
  assert.ok(EV.model_runs >= EV.datasets.length);
});

test('the published headline matches bench/results/per_dataset.csv', () => {
  const rows = perDataset();
  for (const [task, headline] of Object.entries(EV.headline)) {
    const forTask = rows.filter(r => r.task === task);
    assert.equal(headline.datasets, forTask.length, `${task}: dataset count`);
    for (const [key, column] of [['first', 'regret_first'], ['top4', 'regret_top4'],
      ['boosting', 'regret_boosting'], ['random_eligible', 'regret_eligible_mean']]) {
      const got = median(forTask.map(r => r[column]).filter(v => v != null));
      assert.ok(Math.abs(got - headline[key]) < 5e-4, `${task}.${key}: page says ${headline[key]}, data says ${got}`);
    }
  }
});

test('every dataset row on the page is a row in the run', () => {
  const rows = perDataset();
  const byName = new Map(rows.map(r => [`${r.dataset}|${r.task}`, r]));
  for (const d of EV.datasets) {
    const row = byName.get(`${d.dataset}|${d.task}`);
    assert.ok(row, `${d.dataset} is on the page but not in the results`);
    assert.ok(Math.abs(row.best - d.best.score) < 5e-4, `${d.dataset}: best score`);
    assert.equal(row.best_model, d.best.model);
    assert.equal(row.first_model, d.first.model);
  }
});

test('every model in the evidence exists in the taxonomy', () => {
  const known = new Set(T.MODELS.map(m => m.c));
  const unknown = Object.keys(EV.models).filter(code => !known.has(code));
  assert.deepEqual(unknown, []);
  for (const [code, why] of Object.entries(EV.not_runnable)) {
    assert.ok(known.has(code), `${code} is listed as not runnable but is not a model`);
    assert.ok(why.length > 5, `${code} needs a reason`);
  }
});

test('a recommendation can find its measured line, and says nothing when there is none', () => {
  const forest = evidenceFor(T, 'TR2', 'category');
  assert.ok(forest, 'Random Forest ran on classification datasets');
  assert.match(evidenceSentence(forest), /On \d+ classification datasets/);
  // Tasks the benchmark does not cover must not invent a claim.
  assert.equal(evidenceFor(T, 'TR2', 'group'), null);
  assert.equal(evidenceFor(T, 'NN9', 'category'), null, 'U-Net never ran');
  assert.equal(evidenceSentence(null), '');
});

test('the leave-one-dataset-out medians on the page match bench/results/ranking-lodo.csv', () => {
  const rows = readTable('bench/results/ranking-lodo.csv');
  for (const [task, entry] of Object.entries(EV.ranking.tasks)) {
    const forTask = rows.filter(r => r.task === task);
    assert.equal(entry.datasets, forTask.length, `${task}: dataset count`);
    for (const [key, s] of Object.entries(entry.strategies)) {
      const got = median(forTask.map(r => r.best - r[key]).filter(v => !Number.isNaN(v)));
      assert.ok(Math.abs(got - s.median_regret) < 5e-4, `${task}.${key}: page ${s.median_regret}, data ${got}`);
      assert.ok(s.ci[0] <= s.median_regret + 1e-9 && s.median_regret <= s.ci[1] + 1e-9,
        `${task}.${key}: the interval must contain the median`);
    }
  }
});

test('the order in use is tested against every alternative, and the counts add up', () => {
  const rows = readTable('bench/results/ranking-lodo.csv');
  const chosen = EV.ranking.chosen;
  for (const [task, entry] of Object.entries(EV.ranking.tasks)) {
    const forTask = rows.filter(r => r.task === task);
    for (const [other, c] of Object.entries(entry.against_chosen)) {
      assert.notEqual(other, chosen);
      let wins = 0, losses = 0;
      for (const r of forTask) {
        const diff = (r.best - r[other]) - (r.best - r[chosen]);
        if (diff > 1e-9) wins++;
        else if (diff < -1e-9) losses++;
      }
      assert.equal(c.wins, wins, `${task} vs ${other}: wins`);
      assert.equal(c.losses, losses, `${task} vs ${other}: losses`);
      assert.ok(c.p_holm >= c.p - 1e-12 && c.p_holm <= 1, 'Holm can only raise a p-value');
    }
  }
});

test('average ranks on the page can be recomputed from the scores on the page', () => {
  for (const [task, block] of Object.entries(EV.significance)) {
    const models = Object.keys(block.ranks);
    const got = averageRanks(EV.datasets, task, models);
    for (const m of models) {
      assert.ok(Math.abs(got[m] - block.ranks[m]) < 1e-3, `${task} ${m}: page ${block.ranks[m]}, scores give ${got[m]}`);
    }
    const best = Math.min(...Object.values(block.ranks));
    const expected = models.filter(m => block.ranks[m] - best <= block.critical_difference + 1e-9);
    assert.deepEqual([...block.tied_with_best].sort(), expected.sort(), `${task}: tied with the best`);
    assert.equal(block.datasets, EV.datasets.filter(d => d.task === task).length);
  }
});

test('the rank chart marks exactly the models tied with the best, and escapes names', () => {
  const [task, block] = Object.entries(EV.significance)[0];
  const html = rankChart(block, { ...block.names, [Object.keys(block.ranks)[0]]: '<b>x</b>' });
  assert.equal((html.match(/cd-dot in/g) || []).length, block.tied_with_best.length, task);
  assert.equal((html.match(/cd-dot (in|out)/g) || []).length, Object.keys(block.ranks).length);
  assert.ok(!html.includes('<b>x</b>'));
});

test('p-values are shown honestly, and the verdict follows the corrected one', () => {
  assert.equal(formatP(0.465), '0.47');
  assert.equal(formatP(0.0283), '0.028');
  assert.equal(formatP(0.0043), '0.004');
  assert.equal(formatP(2.01e-11), '2.0 × 10⁻¹¹');
  assert.equal(beyondLuck({ p: 0.01, p_holm: 0.06 }), false);
  assert.equal(beyondLuck({ p: 0.01, p_holm: 0.03 }), true);
  const verdict = boostingVerdict(EV.ranking);
  const tests = Object.entries(EV.ranking.tasks).map(([task, entry]) => [task, entry.against_chosen.boosting]);
  for (const [task, c] of tests) assert.ok(verdict.includes(`${c.wins} of`) && verdict.includes(task));
  const beyond = tests.filter(([, c]) => beyondLuck(c)).length;
  if (beyond === 0) assert.match(verdict, /Neither difference is more than luck|within what luck produces/);
  else if (beyond === tests.length) assert.match(verdict, /more than luck\.$/);
  else assert.match(verdict, /^.*Only the .* difference is more than luck\.$/);
});
