// The numbers the site publishes must be the numbers in the committed run.
// evidence.json is generated by bench/dcn/evidence.py; this recomputes the
// headline from bench/results/per_dataset.csv and compares, so the page can
// never quietly disagree with the data behind it.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { parseCSV } from '../site/js/csv.js';
import { evidenceFor, evidenceSentence } from '../site/js/evidence.js';
import { loadTaxonomyFromDisk } from './helpers.js';

const T = loadTaxonomyFromDisk();
const EV = T.EVIDENCE;
const ROOT = new URL('../', import.meta.url);

function perDataset() {
  const { head, body } = parseCSV(fs.readFileSync(new URL('bench/results/per_dataset.csv', ROOT), 'utf8'));
  const index = Object.fromEntries(head.map((name, i) => [name, i]));
  return body.map(row => Object.fromEntries(head.map(name => {
    const raw = row[index[name]];
    const value = raw === '' ? null : Number(raw);
    return [name, Number.isNaN(value) ? raw : value];
  })));
}

const median = (values) => {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = sorted.length / 2;
  return sorted.length % 2 ? sorted[Math.floor(mid)] : (sorted[mid - 1] + sorted[mid]) / 2;
};

test('the evidence file is present and describes its own run', () => {
  assert.ok(EV, 'site/taxonomy/evidence.json is missing');
  assert.match(EV.source_url, /^https:\/\/github\.com\//);
  assert.ok(EV.how.length > 40, 'the method has to be stated on the page');
  assert.ok(EV.datasets.length >= 20);
  assert.ok(EV.model_runs >= EV.datasets.length);
});

test('the published headline matches bench/results/per_dataset.csv', () => {
  const rows = perDataset();
  for (const [task, headline] of Object.entries(EV.headline)) {
    const forTask = rows.filter(r => r.task === task);
    assert.equal(headline.datasets, forTask.length, `${task}: dataset count`);
    for (const [key, column] of [['first', 'regret_first'], ['top4', 'regret_top4'],
      ['boosting', 'regret_boosting'], ['random_eligible', 'regret_eligible_mean']]) {
      const got = median(forTask.map(r => r[column]).filter(v => v != null));
      assert.ok(Math.abs(got - headline[key]) < 5e-4, `${task}.${key}: page says ${headline[key]}, data says ${got}`);
    }
  }
});

test('every dataset row on the page is a row in the run', () => {
  const rows = perDataset();
  const byName = new Map(rows.map(r => [`${r.dataset}|${r.task}`, r]));
  for (const d of EV.datasets) {
    const row = byName.get(`${d.dataset}|${d.task}`);
    assert.ok(row, `${d.dataset} is on the page but not in the results`);
    assert.ok(Math.abs(row.best - d.best.score) < 5e-4, `${d.dataset}: best score`);
    assert.equal(row.best_model, d.best.model);
    assert.equal(row.first_model, d.first.model);
  }
});

test('every model in the evidence exists in the taxonomy', () => {
  const known = new Set(T.MODELS.map(m => m.c));
  const unknown = Object.keys(EV.models).filter(code => !known.has(code));
  assert.deepEqual(unknown, []);
  for (const [code, why] of Object.entries(EV.not_runnable)) {
    assert.ok(known.has(code), `${code} is listed as not runnable but is not a model`);
    assert.ok(why.length > 5, `${code} needs a reason`);
  }
});

test('a recommendation can find its measured line, and says nothing when there is none', () => {
  const forest = evidenceFor(T, 'TR2', 'category');
  assert.ok(forest, 'Random Forest ran on classification datasets');
  assert.match(evidenceSentence(forest), /On \d+ classification datasets/);
  // Tasks the benchmark does not cover must not invent a claim.
  assert.equal(evidenceFor(T, 'TR2', 'group'), null);
  assert.equal(evidenceFor(T, 'NN9', 'category'), null, 'U-Net never ran');
  assert.equal(evidenceSentence(null), '');
});
