// The numbers the site publishes must be the numbers in the committed run.
// evidence.json is generated by bench/dcn/evidence.py; this recomputes the
// headline from bench/results/per_dataset.csv and compares, so the page can
// never quietly disagree with the data behind it.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { parseCSV } from '../site/js/csv.js';
import { averageRanks, beyondLuck, boostingVerdict, choiceNote, evidenceFor, evidenceSentence, formatP, luckWords,
  rankChart, referenceVerdict, seedsNote, subsetNote, unitNoun } from '../site/js/evidence.js';
import { loadTaxonomyFromDisk } from './helpers.js';

const T = loadTaxonomyFromDisk();
const EV = T.EVIDENCE;
const ROOT = new URL('../', import.meta.url);

function readTable(path) {
  const { head, body } = parseCSV(fs.readFileSync(new URL(path, ROOT), 'utf8'));
  const index = Object.fromEntries(head.map((name, i) => [name, i]));
  return body.map(row => Object.fromEntries(head.map(name => {
    const raw = row[index[name]];
    const value = raw === '' ? null : Number(raw);
    return [name, Number.isNaN(value) ? raw : value];
  })));
}

const perDataset = () => readTable('bench/results/per_dataset.csv');

// Mean regret per synthetic family, the unit every published test counts.
// A strategy missing on a dataset (a reference that skipped it) is averaged
// over the members it has, as pandas does; a unit with none is NaN.
function unitRegrets(rows, keys, against = 'best') {
  const groups = new Map();
  for (const r of rows) {
    if (!groups.has(r.family)) groups.set(r.family, []);
    groups.get(r.family).push(r);
  }
  return [...groups.values()].map(members => Object.fromEntries(keys.map(k => {
    const seen = members.filter(r => r[k] != null && r[against] != null);
    return [k, seen.length ? seen.reduce((s, r) => s + (r[against] - r[k]), 0) / seen.length : NaN];
  })));
}

const median = (values) => {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = sorted.length / 2;
  return sorted.length % 2 ? sorted[Math.floor(mid)] : (sorted[mid - 1] + sorted[mid]) / 2;
};

test('the evidence file is present and describes its own run', () => {
  assert.ok(EV, 'site/taxonomy/evidence.json is missing');
  assert.match(EV.source_url, /^https:\/\/github\.com\//);
  assert.ok(EV.how.length > 40, 'the method has to be stated on the page');
  assert.ok(EV.datasets.length >= 20);
  assert.ok(EV.model_runs >= EV.datasets.length);
});

test('the published headline matches bench/results/per_dataset.csv', () => {
  const rows = perDataset();
  for (const [task, headline] of Object.entries(EV.headline)) {
    const forTask = rows.filter(r => r.task === task);
    assert.equal(headline.datasets, forTask.length, `${task}: dataset count`);
    // Mean per synthetic family first: each family counts once.
    const families = new Map();
    for (const r of forTask) families.set(r.family, [...(families.get(r.family) ?? []), r]);
    const units = [...families.values()];
    assert.equal(headline.units, units.length, `${task}: independent units`);
    for (const [key, column] of [['first', 'regret_first'], ['top4', 'regret_top4'],
      ['boosting', 'regret_boosting'], ['random_eligible', 'regret_eligible_mean']]) {
      const got = median(units.map(m => m.reduce((s, r) => s + r[column], 0) / m.length).filter(v => !Number.isNaN(v)));
      assert.ok(Math.abs(got - headline[key]) < 5e-4, `${task}.${key}: page says ${headline[key]}, data says ${got}`);
    }
  }
});

test('every dataset row on the page is a row in the run', () => {
  const rows = perDataset();
  const byName = new Map(rows.map(r => [`${r.dataset}|${r.task}`, r]));
  for (const d of EV.datasets) {
    const row = byName.get(`${d.dataset}|${d.task}`);
    assert.ok(row, `${d.dataset} is on the page but not in the results`);
    assert.ok(Math.abs(row.best - d.best.score) < 5e-4, `${d.dataset}: best score`);
    assert.equal(row.best_model, d.best.model);
    assert.equal(row.first_model, d.first.model);
  }
});

test('every model in the evidence exists in the taxonomy', () => {
  const known = new Set(T.MODELS.map(m => m.c));
  const unknown = Object.keys(EV.models).filter(code => !known.has(code));
  assert.deepEqual(unknown, []);
  for (const [code, why] of Object.entries(EV.not_runnable)) {
    assert.ok(known.has(code), `${code} is listed as not runnable but is not a model`);
    assert.ok(why.length > 5, `${code} needs a reason`);
  }
});

test('a recommendation can find its measured line, and says nothing when there is none', () => {
  const forest = evidenceFor(T, 'TR2', 'category');
  assert.ok(forest, 'Random Forest ran on classification datasets');
  assert.match(evidenceSentence(forest), /On \d+ classification datasets/);
  // Tasks the benchmark does not cover must not invent a claim.
  assert.equal(evidenceFor(T, 'TR2', 'group'), null);
  assert.equal(evidenceFor(T, 'NN9', 'category'), null, 'U-Net never ran');
  assert.equal(evidenceSentence(null), '');
});

test('the leave-one-dataset-out medians on the page match bench/results/ranking-lodo.csv', () => {
  const rows = readTable('bench/results/ranking-lodo.csv');
  for (const [task, entry] of Object.entries(EV.ranking.tasks)) {
    const forTask = rows.filter(r => r.task === task);
    assert.equal(entry.datasets, forTask.length, `${task}: dataset count`);
    const units = unitRegrets(forTask, Object.keys(entry.strategies));
    assert.equal(entry.units, units.length, `${task}: independent units`);
    for (const [key, s] of Object.entries(entry.strategies)) {
      const got = median(units.map(u => u[key]).filter(v => !Number.isNaN(v)));
      assert.ok(Math.abs(got - s.median_regret) < 5e-4, `${task}.${key}: page ${s.median_regret}, data ${got}`);
      assert.ok(s.ci[0] <= s.median_regret + 1e-9 && s.median_regret <= s.ci[1] + 1e-9,
        `${task}.${key}: the interval must contain the median`);
    }
  }
});

test('the order in use is tested against every reference, and the counts add up', () => {
  const rows = readTable('bench/results/ranking-lodo.csv');
  const chosen = EV.ranking.chosen;
  for (const [task, entry] of Object.entries(EV.ranking.tasks)) {
    assert.ok('current' in entry.against_chosen && 'boosting' in entry.against_chosen, task);
    for (const [other, c] of Object.entries(entry.against_chosen)) {
      assert.ok(['current', 'boosting', 'tuned', 'tabpfn'].includes(other), `${task}: ${other} is not a reference`);
      // Only the datasets where both ran, as learn.py compares them.
      const both = rows.filter(r => r.task === task && r[chosen] != null && r[other] != null);
      const units = unitRegrets(both, [chosen, other]);
      assert.equal(c.units, units.length, `${task} vs ${other}: units`);
      assert.notEqual(other, chosen);
      let wins = 0, losses = 0;
      for (const u of units) {
        const diff = u[other] - u[chosen];
        if (diff > 1e-9) wins++;
        else if (diff < -1e-9) losses++;
      }
      assert.equal(c.wins, wins, `${task} vs ${other}: wins`);
      assert.equal(c.losses, losses, `${task} vs ${other}: losses`);
      assert.ok(c.p_holm >= c.p - 1e-12 && c.p_holm <= 1, 'Holm can only raise a p-value');
    }
  }
});

test('average ranks on the page can be recomputed from the scores on the page', () => {
  for (const [task, block] of Object.entries(EV.significance)) {
    const models = Object.keys(block.ranks);
    const got = averageRanks(EV.datasets, task, models);
    for (const m of models) {
      assert.ok(Math.abs(got[m] - block.ranks[m]) < 1e-3, `${task} ${m}: page ${block.ranks[m]}, scores give ${got[m]}`);
    }
    const best = Math.min(...Object.values(block.ranks));
    const expected = models.filter(m => block.ranks[m] - best <= block.critical_difference + 1e-9);
    assert.deepEqual([...block.tied_with_best].sort(), expected.sort(), `${task}: tied with the best`);
    assert.equal(block.datasets, EV.datasets.filter(d => d.task === task).length);
    assert.equal(block.units, new Set(EV.datasets.filter(d => d.task === task).map(d => d.family)).size);
  }
});

test('the rank chart marks exactly the models tied with the best, and escapes names', () => {
  const [task, block] = Object.entries(EV.significance)[0];
  const html = rankChart(block, { ...block.names, [Object.keys(block.ranks)[0]]: '<b>x</b>' });
  assert.equal((html.match(/cd-dot in/g) || []).length, block.tied_with_best.length, task);
  assert.equal((html.match(/cd-dot (in|out)/g) || []).length, Object.keys(block.ranks).length);
  assert.ok(!html.includes('<b>x</b>'));
});

test('p-values are shown honestly, and the verdict follows the corrected one', () => {
  assert.equal(formatP(0.465), '0.47');
  assert.equal(formatP(0.0283), '0.028');
  assert.equal(formatP(0.0043), '0.004');
  assert.equal(formatP(2.01e-11), '2.0 × 10⁻¹¹');
  assert.equal(beyondLuck({ p: 0.01, p_holm: 0.06 }), false);
  assert.equal(beyondLuck({ p: 0.01, p_holm: 0.03 }), true);
  const verdict = boostingVerdict(EV.ranking);
  const tests = Object.entries(EV.ranking.tasks).map(([task, entry]) => [task, entry.against_chosen.boosting]);
  for (const [task, c] of tests) assert.ok(verdict.includes(`${c.wins} of`) && verdict.includes(task));
  const beyond = tests.filter(([, c]) => beyondLuck(c)).length;
  if (beyond === 0) assert.match(verdict, /Neither difference is more than luck|within what luck produces/);
  else if (beyond === tests.length) assert.match(verdict, /more than luck\.$/);
  else assert.match(verdict, /Only the .* difference is more than luck(, and only narrowly)?\.$/);
});

test('the page says how the order in use was chosen, and it agrees with ranking.json', () => {
  const choice = EV.ranking.choice;
  assert.deepEqual(choice, T.RANKING.choice, 'evidence.json and ranking.json disagree about the choice');
  const replaced = choice.filter(d => d.replaced).map(d => d.candidate);
  assert.equal(T.RANKING.chosen, replaced.length ? replaced[replaced.length - 1] : 'prior');
  const note = choiceNote(EV.ranking);
  for (const d of choice) assert.match(note, d.replaced ? /It is the order in use/ : /so it is off/);
  for (const [task, entry] of Object.entries(EV.ranking.tasks)) {
    assert.deepEqual(Object.keys(entry.against_chosen).sort(), ['boosting', 'current'], task);
  }
});

test('what the seeds show is self-consistent, and said in words', () => {
  for (const [task, s] of Object.entries(EV.seeds ?? {})) {
    assert.ok(s.seeds >= 2, task);
    assert.ok(s.flips <= s.compared && s.compared <= s.datasets, task);
    assert.ok(s.same_best >= 0 && s.same_best <= 1, task);
  }
  assert.equal(seedsNote({}), '');
  const note = seedsNote({ classification: { datasets: 5, seeds: 3, score_spread: 0.01, same_best: 0.6, compared: 4, flips: 1 } });
  assert.match(note, /5 classification datasets run under 3 seeds/);
  assert.match(note, /1 of 4/);
});

test('counts say what they count, and a narrow result reads as narrow', () => {
  assert.equal(unitNoun({ datasets: 101, units: 35 }, 'regression'), 'independent regression units');
  assert.equal(unitNoun({ datasets: 94, units: 94 }, 'classification'), 'classification datasets');
  assert.equal(luckWords({ p_holm: 0.046 }), 'more than luck, narrowly');
  assert.equal(luckWords({ p_holm: 0.001 }), 'more than luck');
  assert.equal(luckWords({ p_holm: 0.2 }), 'within what luck produces');
});

test('the gap to the best of everything can be recomputed, and is never negative', () => {
  const rows = readTable('bench/results/ranking-lodo.csv');
  for (const [task, entry] of Object.entries(EV.ranking.tasks)) {
    if (!entry.ceiling) continue;
    const forTask = rows.filter(r => r.task === task);
    const units = unitRegrets(forTask, Object.keys(entry.ceiling), 'ceiling');
    for (const [key, c] of Object.entries(entry.ceiling)) {
      const gaps = units.map(u => u[key]).filter(v => !Number.isNaN(v));
      assert.equal(c.units, gaps.length, `${task}.${key}: units`);
      assert.ok(Math.abs(median(gaps) - c.median_gap) < 5e-4, `${task}.${key}: page ${c.median_gap}, data ${median(gaps)}`);
      assert.ok(gaps.every(g => g >= -1e-9), `${task}.${key}: nothing beats the best of everything`);
    }
  }
});

test('a reference judged on fewer datasets says so, and its verdict names the direction', () => {
  assert.match(subsetNote(20, { datasets: 101, units: 35 }), /only the 20 it ran on/);
  assert.equal(subsetNote(35, { datasets: 101, units: 35 }), '');
  const ranking = { chosen: 'prior', tasks: {
    classification: { datasets: 94, units: 94, against_chosen: { tuned: { wins: 20, losses: 60, ties: 14, p_holm: 0.001 } } },
    regression: { datasets: 101, units: 35, against_chosen: { tuned: { wins: 17, losses: 18, ties: 0, p_holm: 0.9 } } },
  } };
  const verdict = referenceVerdict(ranking, 'tuned', 'tuned boosting');
  assert.match(verdict, /better on 20 of 94 classification datasets/);
  assert.match(verdict, /17 of 35 independent regression units/);
  assert.match(verdict, /More than luck: the classification loss\./);
  assert.equal(referenceVerdict(ranking, 'tabpfn', 'TabPFN'), '', 'no comparison, no sentence');
});
