"""Where each code links to.

No encyclopaedia entries: the links point at things you would actually open
while working, in this order of preference.

  1. the documentation of a library that implements it
     (scikit-learn, PyTorch, statsmodels, river, lifelines, Hugging Face)
  2. the paper that introduced it, on arXiv
  3. the project's own repository on GitHub

Models that map to an estimator in dcn/models.py get their implementation link
generated from the estimator itself (see apply_links.py), so those are correct
by construction. Everything here is checked by tools/check_links.mjs in CI:
anything that does not resolve fails the build rather than sitting there.

A code mapped to None has no link. That is deliberate and a test pins the
list, so a gap is a decision rather than an oversight.
"""

SK = "https://scikit-learn.org/stable/modules/{}.html"
TORCH = "https://pytorch.org/docs/stable/generated/torch.{}.html"
ARXIV = "https://arxiv.org/abs/{}"
RIVER = "https://riverml.xyz/latest/api/drift/{}/"
SM = "https://www.statsmodels.org/stable/{}.html"

# code -> (label, url)
READ: dict[str, tuple[str, str] | None] = {
    # ---- Optimisation and training ---------------------------------------
    "AO1": ("torch.optim.RMSprop", TORCH.format("optim.RMSprop")),
    "AO2": ("torch.optim.Adagrad", TORCH.format("optim.Adagrad")),
    "AO3": ("Learning rate schedules in PyTorch", "https://pytorch.org/docs/stable/optim.html"),
    "AO4": ("torch.optim.LBFGS", TORCH.format("optim.LBFGS")),
    "AO5": ("scipy.sparse.linalg.cg", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.cg.html"),
    "CA3": ("torch.optim.SGD", TORCH.format("optim.SGD")),
    "CA18": ("torch.optim.SGD (momentum)", TORCH.format("optim.SGD")),
    "CA19": ("Adam: A Method for Stochastic Optimization", ARXIV.format("1412.6980")),
    "CA24": ("Batch Normalization (paper)", ARXIV.format("1502.03167")),
    "CA25": ("torch.nn.Dropout", TORCH.format("nn.Dropout")),
    "CA26": ("Perceptron in scikit-learn", SK.format("linear_model")),

    # ---- Calculus and losses ---------------------------------------------
    "CA1": ("Autograd mechanics in PyTorch", "https://pytorch.org/docs/stable/notes/autograd.html"),
    "CA2": ("torch.gradient", TORCH.format("gradient")),
    "CA4": ("Autograd mechanics in PyTorch", "https://pytorch.org/docs/stable/notes/autograd.html"),
    "CA5": ("torch.autograd.functional.jacobian", TORCH.format("autograd.functional.jacobian")),
    "CA6": ("torch.autograd.functional.hessian", TORCH.format("autograd.functional.hessian")),
    "CA7": ("torch.nn.Conv1d", TORCH.format("nn.Conv1d")),
    "CA8": ("torch.nn.MSELoss", TORCH.format("nn.MSELoss")),
    "CA9": ("torch.nn.CrossEntropyLoss", TORCH.format("nn.CrossEntropyLoss")),
    "CA10": ("torch.nn.Sigmoid", TORCH.format("nn.Sigmoid")),
    "CA11": ("torch.nn.Softmax", TORCH.format("nn.Softmax")),
    "CA12": ("torch.nn.ReLU", TORCH.format("nn.ReLU")),
    "CA13": ("torch.nn.GELU", TORCH.format("nn.GELU")),
    "CA14": ("scipy.optimize.minimize (constraints)", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html"),
    "CA15": ("torch.nn.Tanh", TORCH.format("nn.Tanh")),
    "CA16": ("torch.nn.LeakyReLU", TORCH.format("nn.LeakyReLU")),
    "CA17": ("torch.nn.SiLU", TORCH.format("nn.SiLU")),
    "CA20": ("sklearn.metrics.hinge_loss", "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.hinge_loss.html"),
    "CA21": ("torch.nn.HuberLoss", TORCH.format("nn.HuberLoss")),
    "CA22": ("torch.nn.BCELoss", TORCH.format("nn.BCELoss")),
    "CA23": ("Elastic net in scikit-learn", SK.format("linear_model")),
    "CA27": ("scipy.interpolate.approximate_taylor_polynomial",
             "https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.approximate_taylor_polynomial.html"),

    # ---- Attention and sequence models ------------------------------------
    "AT1": ("Attention Is All You Need", ARXIV.format("1706.03762")),
    "AT2": ("torch.nn.MultiheadAttention", TORCH.format("nn.MultiheadAttention")),
    "AT3": ("Attention Is All You Need", ARXIV.format("1706.03762")),
    "AT4": ("torch.nn.LayerNorm", TORCH.format("nn.LayerNorm")),
    "AT5": ("Deep Residual Learning", ARXIV.format("1512.03385")),

    # ---- Association rules -------------------------------------------------
    "AR1": ("mlxtend association rules", "https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/"),
    "AR2": ("mlxtend association rules", "https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/"),
    "AR3": ("mlxtend association rules", "https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/"),

    # ---- Dependence, diffusion, game theory --------------------------------
    "DM1": ("copulas (the library)", "https://github.com/sdv-dev/Copulas"),
    "DF1": ("Denoising Diffusion Probabilistic Models", ARXIV.format("2006.11239")),
    "DF2": ("Diffusers documentation", "https://huggingface.co/docs/diffusers/index"),
    "DF3": ("Score-Based Generative Modeling through SDEs", ARXIV.format("2011.13456")),
    "DF4": ("Score-Based Generative Modeling through SDEs", ARXIV.format("2011.13456")),
    "GM1": ("Generative Adversarial Networks", ARXIV.format("1406.2661")),
    "GM2": ("nashpy (the library)", "https://github.com/drvinceknight/Nashpy"),

    # ---- Graphs -------------------------------------------------------------
    "GT1": ("networkx adjacency matrix", "https://networkx.org/documentation/stable/reference/convert.html"),
    "GT2": ("networkx Laplacian matrix", "https://networkx.org/documentation/stable/reference/linalg.html"),
    "GT3": ("networkx shortest paths", "https://networkx.org/documentation/stable/reference/algorithms/shortest_paths.html"),
    "GT4": ("networkx PageRank", "https://networkx.org/documentation/stable/reference/algorithms/link_analysis.html"),
    "GT5": ("networkx centrality", "https://networkx.org/documentation/stable/reference/algorithms/centrality.html"),

    # ---- Information theory --------------------------------------------------
    "IT1": ("scipy.stats.entropy", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.entropy.html"),
    "IT2": ("Decision trees in scikit-learn", SK.format("tree")),
    "IT3": ("torch.nn.CrossEntropyLoss", TORCH.format("nn.CrossEntropyLoss")),
    "IT4": ("torch.nn.KLDivLoss", TORCH.format("nn.KLDivLoss")),
    "IT5": ("torch.logsumexp", TORCH.format("logsumexp")),
    "IT6": ("sklearn.metrics.mutual_info_score",
            "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mutual_info_score.html"),
    "IT7": ("Perplexity in the Hugging Face docs", "https://huggingface.co/docs/transformers/perplexity"),

    # ---- Linear algebra and distances ----------------------------------------
    "LA1": ("numpy.dot", "https://numpy.org/doc/stable/reference/generated/numpy.dot.html"),
    "LA2": ("numpy.matmul", "https://numpy.org/doc/stable/reference/generated/numpy.matmul.html"),
    "LA3": ("numpy.linalg.norm", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html"),
    "LA4": ("numpy.linalg.norm", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html"),
    "LA5": ("numpy.linalg.eig", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html"),
    "LA6": ("numpy.linalg.svd", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html"),
    "LA7": ("numpy.multiply", "https://numpy.org/doc/stable/reference/generated/numpy.multiply.html"),
    "LA8": ("sklearn.metrics.pairwise.cosine_similarity",
            "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html"),
    "LA9": ("scipy.spatial.distance.euclidean",
            "https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.euclidean.html"),
    "LA10": ("numpy.cov", "https://numpy.org/doc/stable/reference/generated/numpy.cov.html"),
    "LA11": ("numpy.transpose", "https://numpy.org/doc/stable/reference/generated/numpy.transpose.html"),
    "LA12": ("numpy.linalg.inv", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html"),
    "LA13": ("numpy.linalg.det", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html"),
    "LA14": ("numpy.trace", "https://numpy.org/doc/stable/reference/generated/numpy.trace.html"),
    "LA15": ("numpy.linalg.matrix_rank", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_rank.html"),
    "LA16": ("numpy.linalg.qr", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html"),
    "LA17": ("numpy.vdot", "https://numpy.org/doc/stable/reference/generated/numpy.vdot.html"),
    "LA18": ("numpy.linalg.norm", "https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html"),
    "LA19": ("scipy.spatial.distance.cityblock",
             "https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cityblock.html"),
    "LA20": ("scipy.spatial.distance.minkowski",
             "https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.minkowski.html"),
    "LA21": ("scipy.spatial.distance.mahalanobis",
             "https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.mahalanobis.html"),
    "LA22": ("sklearn.metrics.pairwise.rbf_kernel",
             "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.rbf_kernel.html"),
    "LA23": ("sklearn.metrics.pairwise.polynomial_kernel",
             "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.polynomial_kernel.html"),

    # ---- Probability and statistics -------------------------------------------
    "PS1": ("Naive Bayes in scikit-learn", SK.format("naive_bayes")),
    "PS2": ("scipy.stats.norm", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html"),
    "PS3": ("scipy.stats.fit", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html"),
    "PS4": ("numpy.var", "https://numpy.org/doc/stable/reference/generated/numpy.var.html"),
    "PS5": ("sklearn.metrics.mean_absolute_error",
            "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html"),
    "PS6": ("scipy.stats.chisquare", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisquare.html"),
    "PS7": ("scipy.stats.ks_2samp", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html"),
    "PS8": ("Population stability index in Evidently",
            "https://github.com/evidentlyai/evidently"),
    "PS9": ("scipy.stats.multivariate_normal",
            "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multivariate_normal.html"),
    "PS10": ("scipy.stats.multivariate_normal",
             "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multivariate_normal.html"),
    "PS11": ("numpy.mean", "https://numpy.org/doc/stable/reference/generated/numpy.mean.html"),
    "PS12": ("numpy.std", "https://numpy.org/doc/stable/reference/generated/numpy.std.html"),
    "PS13": ("scipy.stats.pearsonr", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html"),
    "PS14": ("sklearn.preprocessing.StandardScaler",
             "https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html"),
    "PS15": ("scipy.stats.ttest_ind", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html"),
    "PS16": ("scipy.stats.poisson", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.poisson.html"),
    "PS17": ("scipy.stats.binom", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom.html"),
    "PS18": ("scipy.stats.wasserstein_distance",
             "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wasserstein_distance.html"),
    "PS19": ("scipy.spatial.distance.jensenshannon",
             "https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.jensenshannon.html"),
    "PS20": ("scipy.stats.bootstrap", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html"),
    "PS21": ("scipy.stats.f_oneway", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f_oneway.html"),

    # ---- Reinforcement learning ------------------------------------------------
    "RL1": ("Gymnasium documentation", "https://gymnasium.farama.org/"),
    "RL2": ("Q-learning in Stable-Baselines3 docs", "https://stable-baselines3.readthedocs.io/en/master/"),
    "RL3": ("Gymnasium documentation", "https://gymnasium.farama.org/"),
    "RL4": ("Proximal Policy Optimization", ARXIV.format("1707.06347")),
    "RL5": ("Gymnasium documentation", "https://gymnasium.farama.org/"),

    # ---- Signal processing --------------------------------------------------------
    "SP1": ("scipy.fft", "https://docs.scipy.org/doc/scipy/reference/fft.html"),
    "SP2": ("scipy.fft.fft", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fft.html"),
    "SP3": ("scipy.signal.stft", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html"),
    "SP4": ("librosa.feature.mfcc", "https://librosa.org/doc/latest/generated/librosa.feature.mfcc.html"),

    # ---- Survival analysis ----------------------------------------------------------
    "SA1": ("lifelines documentation", "https://lifelines.readthedocs.io/en/latest/"),
    "SA2": ("lifelines documentation", "https://lifelines.readthedocs.io/en/latest/"),
    "SA3": ("lifelines KaplanMeierFitter", "https://lifelines.readthedocs.io/en/latest/fitters/univariate/KaplanMeierFitter.html"),

    # ---- Time series ------------------------------------------------------------------
    "TS1": ("statsmodels.tsa.stattools.acf", SM.format("generated/statsmodels.tsa.stattools.acf")),
    "TS2": ("statsmodels time series analysis", SM.format("tsa")),
    "TS3": ("statsmodels ARIMA", SM.format("generated/statsmodels.tsa.arima.model.ARIMA")),
    "TS4": ("statsmodels AutoReg", SM.format("generated/statsmodels.tsa.ar_model.AutoReg")),
    "TS5": ("statsmodels ExponentialSmoothing",
            SM.format("generated/statsmodels.tsa.holtwinters.ExponentialSmoothing")),

    # ---- Models without an estimator in the registry ------------------------------------
    "LM6": ("Polynomial features in scikit-learn", SK.format("linear_model")),
    "TR4": ("Outlier detection in scikit-learn", SK.format("outlier_detection")),
    "EN5": ("CatBoost on GitHub", "https://github.com/catboost/catboost"),
    "SV3": ("Outlier detection in scikit-learn", SK.format("outlier_detection")),
    "PR2": ("Gaussian mixture models in scikit-learn", SK.format("mixture")),
    "PR3": ("hmmlearn documentation", "https://hmmlearn.readthedocs.io/en/latest/"),
    "PR4": ("pgmpy on GitHub", "https://github.com/pgmpy/pgmpy"),
    "PR5": ("sklearn-crfsuite documentation", "https://sklearn-crfsuite.readthedocs.io/en/latest/"),
    "IB2": ("scikit-learn-extra KMedoids", "https://github.com/scikit-learn-contrib/scikit-learn-extra"),
    "CL1": ("Clustering in scikit-learn", SK.format("clustering")),
    "CL2": ("Clustering in scikit-learn", SK.format("clustering")),
    "CL3": ("Clustering in scikit-learn", SK.format("clustering")),
    "CL4": ("Clustering in scikit-learn", SK.format("clustering")),
    "DR1": ("Decomposition in scikit-learn", SK.format("decomposition")),
    "DR2": ("Manifold learning in scikit-learn", SK.format("manifold")),
    "DR3": ("UMAP documentation", "https://umap-learn.readthedocs.io/en/latest/"),
    "DR5": ("Autoencoders in the PyTorch examples", "https://github.com/pytorch/examples"),
    "NN3": ("torch.nn.Conv2d", TORCH.format("nn.Conv2d")),
    "NN4": ("torch.nn.RNN", TORCH.format("nn.RNN")),
    "NN5": ("torch.nn.LSTM", TORCH.format("nn.LSTM")),
    "NN6": ("torch.nn.GRU", TORCH.format("nn.GRU")),
    "NN7": ("torch.nn.Transformer", TORCH.format("nn.Transformer")),
    "NN8": ("Deep Residual Learning", ARXIV.format("1512.03385")),
    "NN9": ("U-Net: Convolutional Networks for Biomedical Image Segmentation", ARXIV.format("1505.04597")),
    "NN10": ("Siamese networks in the PyTorch examples", "https://github.com/pytorch/examples"),
    "NN11": ("MiniSom on GitHub", "https://github.com/JustGlowing/minisom"),
    "NN12": ("Generative Adversarial Networks", ARXIV.format("1406.2661")),
    "NN13": ("Auto-Encoding Variational Bayes", ARXIV.format("1312.6114")),
    "NN14": ("Diffusers documentation", "https://huggingface.co/docs/diffusers/index"),
    "NLP1": ("Efficient Estimation of Word Representations in Vector Space", ARXIV.format("1301.3781")),
    "NLP2": ("BERT in the Hugging Face docs", "https://huggingface.co/docs/transformers/model_doc/bert"),
    "NLP3": ("GPT-2 in the Hugging Face docs", "https://huggingface.co/docs/transformers/model_doc/gpt2"),
    "GR1": ("PyTorch Geometric documentation", "https://pytorch-geometric.readthedocs.io/en/latest/"),
    "GR2": ("Semi-Supervised Classification with Graph Convolutional Networks", ARXIV.format("1609.02907")),
    "GR3": ("Graph Attention Networks", ARXIV.format("1710.10903")),
    "RLM1": ("Stable-Baselines3 documentation", "https://stable-baselines3.readthedocs.io/en/master/"),
    "RLM2": ("Playing Atari with Deep Reinforcement Learning", ARXIV.format("1312.5602")),
    "RLM3": ("Proximal Policy Optimization", ARXIV.format("1707.06347")),
    "RLM4": ("Stable-Baselines3 documentation", "https://stable-baselines3.readthedocs.io/en/master/"),
    "RLM5": ("Mastering the game of Go (AlphaGo Zero)", "https://www.nature.com/articles/nature24270"),
    "TSM1": ("statsmodels ARIMA", SM.format("generated/statsmodels.tsa.arima.model.ARIMA")),
    "TSM2": ("statsmodels ExponentialSmoothing",
             SM.format("generated/statsmodels.tsa.holtwinters.ExponentialSmoothing")),
    "TSM3": ("Prophet on GitHub", "https://github.com/facebook/prophet"),
    "SA-M1": ("lifelines CoxPHFitter", "https://lifelines.readthedocs.io/en/latest/fitters/regression/CoxPHFitter.html"),
    "SA-M2": ("lifelines KaplanMeierFitter",
              "https://lifelines.readthedocs.io/en/latest/fitters/univariate/KaplanMeierFitter.html"),

    # ---- Drift checkers -------------------------------------------------------------------
    "DR-M1": ("scipy.stats.ks_2samp", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html"),
    "DR-M2": ("Evidently on GitHub", "https://github.com/evidentlyai/evidently"),
    "DR-M3": ("scipy.stats.chi2_contingency",
              "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2_contingency.html"),
    "DR-M4": ("scipy.stats.wasserstein_distance",
              "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wasserstein_distance.html"),
    "DR-M5": ("scipy.spatial.distance.jensenshannon",
              "https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.jensenshannon.html"),
    "DR-M6": ("scipy.stats.entropy", "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.entropy.html"),
    "DR-M7": ("Alibi Detect on GitHub", "https://github.com/SeldonIO/alibi-detect"),
    "DR-M8": ("scipy.stats.anderson_ksamp",
              "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson_ksamp.html"),
    "DR-M9": ("scipy.stats.mannwhitneyu",
              "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html"),
    "DR-M10": ("scipy.stats.cramervonmises_2samp",
               "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.cramervonmises_2samp.html"),
    "DR-M11": ("Alibi Detect on GitHub", "https://github.com/SeldonIO/alibi-detect"),
    "DR-M12": ("scipy.stats.cramervonmises_2samp",
               "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.cramervonmises_2samp.html"),
    "DR-M13": ("scipy.stats.anderson_ksamp",
               "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson_ksamp.html"),
    "DR-M14": ("scipy.stats.energy_distance",
               "https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.energy_distance.html"),
    "DR-C1": ("river drift.binary.DDM", "https://riverml.xyz/latest/api/drift/binary/DDM/"),
    "DR-C2": ("river drift.binary.EDDM", "https://riverml.xyz/latest/api/drift/binary/EDDM/"),
    "DR-C3": ("river drift.PageHinkley", RIVER.format("PageHinkley")),
    "DR-C4": ("river drift.ADWIN", RIVER.format("ADWIN")),
    "DR-C5": ("river drift.KSWIN", RIVER.format("KSWIN")),
    "DR-C6": ("river drift.binary.HDDM_A", "https://riverml.xyz/latest/api/drift/binary/HDDM-A/"),
    "DR-C7": ("river drift.binary.HDDM_W", "https://riverml.xyz/latest/api/drift/binary/HDDM-W/"),
    "DR-C8": ("river on GitHub", "https://github.com/online-ml/river"),
    "DR-C9": ("river on GitHub", "https://github.com/online-ml/river"),
    "DR-S1": ("river on GitHub", "https://github.com/online-ml/river"),
    "DR-S2": ("river on GitHub", "https://github.com/online-ml/river"),
    "DR-S3": ("river drift.PageHinkley", RIVER.format("PageHinkley")),
    "DR-S4": ("river drift.ADWIN", RIVER.format("ADWIN")),
    "DR-S5": ("river on GitHub", "https://github.com/online-ml/river"),
    "DR-S6": ("river on GitHub", "https://github.com/online-ml/river"),
    "DR-S7": ("river on GitHub", "https://github.com/online-ml/river"),
    "DR-MV1": ("scipy.spatial.distance.mahalanobis",
               "https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.mahalanobis.html"),
    "DR-MV2": ("Decomposition in scikit-learn", SK.format("decomposition")),
    "DR-A1": ("Evidently on GitHub", "https://github.com/evidentlyai/evidently"),
    "DR-A2": ("Evidently on GitHub", "https://github.com/evidentlyai/evidently"),
    "DR-CV1": ("Evidently on GitHub", "https://github.com/evidentlyai/evidently"),
    "DR-D1": ("Alibi Detect on GitHub", "https://github.com/SeldonIO/alibi-detect"),
    "DR-D2": ("Alibi Detect on GitHub", "https://github.com/SeldonIO/alibi-detect"),
    "DR-DL1": ("Alibi Detect on GitHub", "https://github.com/SeldonIO/alibi-detect"),
    "DR-DL2": ("Alibi Detect on GitHub", "https://github.com/SeldonIO/alibi-detect"),
    "DR-R1": ("Evidently on GitHub", "https://github.com/evidentlyai/evidently"),
    "DR-R2": ("Evidently on GitHub", "https://github.com/evidentlyai/evidently"),

    # ---- Pipelines ------------------------------------------------------------------------------
    "PL-T1": ("Apache Airflow documentation", "https://airflow.apache.org/docs/"),
    "PL-T2": ("Feast, the feature store", "https://github.com/feast-dev/feast"),
    "PL-T3": ("Feature extraction in scikit-learn", SK.format("feature_extraction")),
    "PL-T4": ("Optuna documentation", "https://optuna.readthedocs.io/en/stable/"),
    "PL-T5": ("Cross-validation in scikit-learn", SK.format("cross_validation")),
    "PL-T6": ("MLflow documentation", "https://mlflow.org/docs/latest/index.html"),
    "PL-T7": ("BentoML on GitHub", "https://github.com/bentoml/BentoML"),
    "PL-T8": ("Kubeflow Pipelines on GitHub", "https://github.com/kubeflow/pipelines"),
    "PL-T9": ("Evidently on GitHub", "https://github.com/evidentlyai/evidently"),
    "PL-T10": ("MLflow documentation", "https://mlflow.org/docs/latest/index.html"),
    "PL-T11": ("Label Studio on GitHub", "https://github.com/HumanSignal/label-studio"),
    "PL-T12": ("RAG in the Hugging Face docs", "https://huggingface.co/docs/transformers/model_doc/rag"),
    "PL-T13": ("TRL, fine-tuning with Hugging Face", "https://huggingface.co/docs/trl/index"),
    "PL-T14": ("Statistical tests in SciPy", "https://docs.scipy.org/doc/scipy/reference/stats.html"),

    # ---- Data axis codes --------------------------------------------------------------------------
    "A11": ("Supervised learning in scikit-learn", "https://scikit-learn.org/stable/supervised_learning.html"),
    "A12": ("Unsupervised learning in scikit-learn", "https://scikit-learn.org/stable/unsupervised_learning.html"),
    "A13": ("Snorkel, programmatic labelling", "https://github.com/snorkel-team/snorkel"),
    "A14": ("Semi-supervised learning in scikit-learn", SK.format("semi_supervised")),
    "A15": ("Self-supervised learning in the Hugging Face docs",
            "https://huggingface.co/docs/transformers/tasks/masked_language_modeling"),
    "A21": ("Cross-validation in scikit-learn", SK.format("cross_validation")),
    "A22": ("statsmodels time series analysis", SM.format("tsa")),
    "A23": ("GeoPandas documentation", "https://geopandas.org/en/stable/"),
    "A24": ("networkx documentation", "https://networkx.org/documentation/stable/"),
    "A25": ("pandas MultiIndex", "https://pandas.pydata.org/docs/user_guide/advanced.html"),
    "A26": ("Feature extraction in scikit-learn", SK.format("feature_extraction")),
    "A31": ("Preprocessing in scikit-learn", SK.format("preprocessing")),
    "A32": ("Encoding categorical features in scikit-learn", SK.format("preprocessing")),
    "A33": ("OrdinalEncoder in scikit-learn",
            "https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OrdinalEncoder.html"),
    "A34": ("Text feature extraction in scikit-learn", SK.format("feature_extraction")),
    "A35": ("torchvision documentation", "https://pytorch.org/vision/stable/index.html"),
    "A36": ("librosa documentation", "https://librosa.org/doc/latest/index.html"),
    "A37": ("PyTorch Geometric documentation", "https://pytorch-geometric.readthedocs.io/en/latest/"),
    "A38": ("ColumnTransformer in scikit-learn",
            "https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html"),
    "A41": None,
    "A42": ("Feature selection in scikit-learn", SK.format("feature_selection")),
    "A43": ("scipy.sparse", "https://docs.scipy.org/doc/scipy/reference/sparse.html"),
    "A44": None,
    "A51": ("Model evaluation in scikit-learn", SK.format("model_evaluation")),
    "A52": ("imbalanced-learn documentation", "https://imbalanced-learn.org/stable/"),
    "A53": ("statsmodels stationarity tests", SM.format("tsa")),
    "A54": ("Evidently on GitHub", "https://github.com/evidentlyai/evidently"),
    "A55": ("Linear models in scikit-learn", SK.format("linear_model")),
    "A56": ("Kernel methods in scikit-learn", SK.format("svm")),
    "A61": None,
    "A62": ("Imputation in scikit-learn", SK.format("impute")),
    "A63": ("Imputation in scikit-learn", SK.format("impute")),
    "A64": ("Preprocessing in scikit-learn", SK.format("preprocessing")),
}
